name: Release & Publish Node.js Package (GPR, Restricted)

on:
  push:
    tags:
      - "v*.*.*"           # Triggers on version tags like v1.2.3
    branches:
      - main               # Optionally allow manual dispatch on main
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Needed for creating GitHub Releases
      packages: write      # Needed to publish to GPR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@${{ github.repository_owner }}'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build --if-present

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

      - name: Publish to GitHub Package Registry (restricted)
        if: startsWith(github.ref, 'refs/tags/') && github.ref_protected == true
        run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}